[package]
name = "bjira"
version = "0.1.0"
authors = ["Okan Akdogan <okan.akdogan@arcelik.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
mongodb = "1.2.1"
cargo-watch = "7.7.1"