version: '3'
services:
    web:
      build: .
      entrypoint: [cargo, watch, -x, 'run --bin bjira']
      volumes: 
        - .:/usr/src/bjira
      ports:
        - "8080:8080"
      links:
        - db
    db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      